--(new)BB_LIKE

DROP TABLE BB_LIKE
CASCADE CONSTRAINT;

DROP SEQUENCE BB_LIKE;

CREATE TABLE BB_LIKE(
	SEQ NUMBER(10) PRIMARY KEY,
	MEMBER_SEQ NUMBER(20) NOT NULL,
	BBS_SEQ NUMBER(10) NOT NULL
);

INSERT INTO BB_LIKE
VALUES(1,1,1);

DELETE FROM BB_LIKE
WHERE MEMBER_SEQ=1 AND BBS_SEQ=1;

CREATE SEQUENCE BB_LIKE_SEQ
START WITH 1
INCREMENT BY 1;

--foreign key 추가 
ALTER TABLE BB_LIKE
ADD CONSTRAINT FK_BB_B_LIKE_SEQ FOREIGN KEY(BBS_SEQ)
REFERENCES BB_BBS(SEQ);

ALTER TABLE BB_LIKE
ADD CONSTRAINT FK_BB_M_LIKE_SEQ FOREIGN KEY(MEMBER_SEQ)
REFERENCES BB_MEMBER(SEQ);
--foreign key 추가 

--(old)BB_LIKE

SELECT * FROM BB_LIKE;

DROP TABLE BB_LIKE
CASCADE CONSTRAINT;

DROP SEQUENCE BB_LIKE_SEQ;

CREATE TABLE BB_LIKE(
	SEQ NUMBER(10) PRIMARY KEY,
	ID VARCHAR2(20) NOT NULL,
	BBS_SEQ NUMBER(10) NOT NULL
);

CREATE SEQUENCE BB_LIKE_SEQ
START WITH 1
INCREMENT BY 1;
